title: Quotes
modelClass: Katana\Quotes\Models\Quotes
list: $/katana/quotes/models/quotes/columns.yaml
recordUrl: 'katana/quotes/quotes/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
